apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base2
  namespace: argocd2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'git@github.com:cactiuser1/123.git'
    path: argocd/
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy: { }
